<?php

define('DEBUG', true);

define('DB_DRIVER', 'MYSQL||POSTGRESS||SQLSERVER||ORACLE');
define('DB_HOSTNAME', 'NUMERODOHOSTDOBANCO');
define('DB_DATABASE', 'NOMEDOSEUBANCOAQUI');
define('DB_USERNAME', 'SEUUSUARIODOBANCO');
define('DB_PASSWORD', 'SUASENHADOBANCO');